[global]
  sendAnonymousUsage = false
[providers.docker]
  exposedByDefault = false

# Entry points
[entryPoints.web]
  address = ":80"
[entryPoints.web-secure]
  address = ":443"
[entryPoints.smtp]
  address = ":25"

# Redirect 80 to 443
[entryPoints.web.http.redirections.entryPoint]
  to = "web-secure"
  permanent = true
  scheme = "https"

[certificatesResolvers.le-resolver.acme]
  storage = '/etc/traefik/acme/acme.json'
  tlsChallenge = true

[providers.file]
  filename = "/etc/traefik/dynamic.toml"