# Entry points
[entryPoints.web]
  address = ":80"
[entryPoints.web-secure]
  address = ":443"
[entryPoints.smtp-tls]
  address = ":587"

# Redirect 80 to 443
[entryPoints.web.http.redirections.entryPoint]
  to = "web-secure"
  permanent = true
  scheme = "https"

[global]
  sendAnonymousUsage = false

[providers.docker]

[certificatesResolvers.mytlschallenge.acme]
  storage = '/etc/traefik/acme/acme.json'
  tlsChallenge = true

[providers.file]
  filename = "/etc/traefik/dynamic.toml"